// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserColorPreferences.API.Data;

namespace UserColorPreferences.API.Migrations
{
    [DbContext(typeof(UserColorPreferencesContext))]
    partial class UserColorPreferencesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("UserColorPreferences.API.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("tinyint")
                        .HasColumnName("Age");

                    b.Property<string>("FavoriteColor")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FavoriteColor");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IDX_Users_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
